name: Zhou Ye
markdown: kramdown
kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# Google Analytics
google_analytics: G-5RMR47M0J3 # Add your GA4 Measurement ID here (e.g., G-XXXXXXXXXX)
